name: xftts_fluttify_example
description: Demonstrates how to use the xftts_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  decorated_flutter: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  xftts_fluttify:
    path: ../

flutter:
  uses-material-design: true