name: xftts_fluttify
description: A `xftts` flutter plugin, Powered by `Fluttify` engine.
version: 0.1.2
author: yohom <yohombao@qq.com>
homepage: https://fluttify.com

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttify.xftts_fluttify
        pluginClass: XfttsFluttifyPlugin
      ios:
        pluginClass: XfttsFluttifyPlugin